-- Typed JSON business tables with SQL constraints and transactional change capture.
CREATE TABLE changes(sequence INTEGER PRIMARY KEY AUTOINCREMENT,table_name TEXT NOT NULL,row_id TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),occurred_at TEXT NOT NULL);
CREATE TABLE operations(actor_id TEXT NOT NULL,operation_id TEXT NOT NULL,fingerprint TEXT NOT NULL,response TEXT NOT NULL,status INTEGER NOT NULL,PRIMARY KEY(actor_id,operation_id));
CREATE TABLE mutation_checks(ok INTEGER NOT NULL CHECK(ok=1));
CREATE TABLE device_credentials(device_id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE);
CREATE TABLE invite_credentials(invite_id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE);
CREATE TABLE admin_sessions(id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL);
CREATE TABLE login_limits(bucket TEXT PRIMARY KEY,failures INTEGER NOT NULL,window_start INTEGER NOT NULL);
CREATE TABLE participants(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER participants_insert_feed AFTER INSERT ON participants BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('participants',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER participants_update_feed AFTER UPDATE ON participants BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('participants',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE works(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER works_insert_feed AFTER INSERT ON works BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('works',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER works_update_feed AFTER UPDATE ON works BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('works',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE versions(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER versions_insert_feed AFTER INSERT ON versions BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('versions',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER versions_update_feed AFTER UPDATE ON versions BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('versions',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE entities(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER entities_insert_feed AFTER INSERT ON entities BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('entities',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER entities_update_feed AFTER UPDATE ON entities BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('entities',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE aliases(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER aliases_insert_feed AFTER INSERT ON aliases BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('aliases',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER aliases_update_feed AFTER UPDATE ON aliases BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('aliases',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE credits(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER credits_insert_feed AFTER INSERT ON credits BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('credits',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER credits_update_feed AFTER UPDATE ON credits BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('credits',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE responses(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER responses_insert_feed AFTER INSERT ON responses BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('responses',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER responses_update_feed AFTER UPDATE ON responses BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('responses',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE tags(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER tags_insert_feed AFTER INSERT ON tags BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('tags',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER tags_update_feed AFTER UPDATE ON tags BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('tags',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE tag_assignments(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER tag_assignments_insert_feed AFTER INSERT ON tag_assignments BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('tag_assignments',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER tag_assignments_update_feed AFTER UPDATE ON tag_assignments BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('tag_assignments',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE sources(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER sources_insert_feed AFTER INSERT ON sources BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('sources',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER sources_update_feed AFTER UPDATE ON sources BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('sources',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE research_results(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER research_results_insert_feed AFTER INSERT ON research_results BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('research_results',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER research_results_update_feed AFTER UPDATE ON research_results BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('research_results',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE research_jobs(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER research_jobs_insert_feed AFTER INSERT ON research_jobs BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('research_jobs',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER research_jobs_update_feed AFTER UPDATE ON research_jobs BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('research_jobs',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE usage(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER usage_insert_feed AFTER INSERT ON usage BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('usage',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER usage_update_feed AFTER UPDATE ON usage BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('usage',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE devices(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER devices_insert_feed AFTER INSERT ON devices BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('devices',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER devices_update_feed AFTER UPDATE ON devices BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('devices',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE invites(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER invites_insert_feed AFTER INSERT ON invites BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('invites',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER invites_update_feed AFTER UPDATE ON invites BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('invites',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE audit(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER audit_insert_feed AFTER INSERT ON audit BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('audit',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER audit_update_feed AFTER UPDATE ON audit BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('audit',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE audit_corrections(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER audit_corrections_insert_feed AFTER INSERT ON audit_corrections BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('audit_corrections',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER audit_corrections_update_feed AFTER UPDATE ON audit_corrections BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('audit_corrections',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TABLE sync_status(id TEXT PRIMARY KEY,data TEXT NOT NULL CHECK(json_valid(data) AND json_extract(data,'$.id')=id),revision INTEGER GENERATED ALWAYS AS(json_extract(data,'$.revision')) STORED);
CREATE TRIGGER sync_status_insert_feed AFTER INSERT ON sync_status BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('sync_status',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE TRIGGER sync_status_update_feed AFTER UPDATE ON sync_status BEGIN INSERT INTO changes(table_name,row_id,data,occurred_at) VALUES('sync_status',NEW.id,NEW.data,json_extract(NEW.data,'$.updated_at')); END;
CREATE UNIQUE INDEX participant_name_active ON participants(lower(trim(json_extract(data,'$.name')))) WHERE json_extract(data,'$.deleted_at') IS NULL;
CREATE UNIQUE INDEX version_reference_active ON versions(json_extract(data,'$.reference_url')) WHERE json_extract(data,'$.deleted_at') IS NULL AND json_extract(data,'$.reference_url') IS NOT NULL;
CREATE UNIQUE INDEX response_active_daily ON responses(json_extract(data,'$.participant_id'),json_extract(data,'$.version_id'),json_extract(data,'$.record_date')) WHERE json_extract(data,'$.deleted_at') IS NULL AND json_extract(data,'$.version_id') IS NOT NULL;
CREATE UNIQUE INDEX unresolved_active_daily ON responses(json_extract(data,'$.participant_id'),lower(trim(json_extract(data,'$.unresolved_title'))),coalesce(lower(trim(json_extract(data,'$.artist_hint'))),''),coalesce(json_extract(data,'$.reference_url'),''),json_extract(data,'$.record_date')) WHERE json_extract(data,'$.deleted_at') IS NULL AND json_extract(data,'$.version_id') IS NULL;
CREATE INDEX response_participant_date ON responses(json_extract(data,'$.participant_id'),json_extract(data,'$.record_date'));
CREATE UNIQUE INDEX alias_active_unique ON aliases(json_extract(data,'$.entity_id'),lower(trim(json_extract(data,'$.name')))) WHERE json_extract(data,'$.deleted_at') IS NULL;
CREATE UNIQUE INDEX credit_active_unique ON credits(json_extract(data,'$.version_id'),json_extract(data,'$.entity_id'),json_extract(data,'$.role')) WHERE json_extract(data,'$.deleted_at') IS NULL;
CREATE UNIQUE INDEX tag_assignment_active_unique ON tag_assignments(json_extract(data,'$.version_id'),json_extract(data,'$.tag_id')) WHERE json_extract(data,'$.deleted_at') IS NULL;
CREATE UNIQUE INDEX job_version_unique ON research_jobs(json_extract(data,'$.version_id')) WHERE json_extract(data,'$.deleted_at') IS NULL AND json_extract(data,'$.version_id') IS NOT NULL;
CREATE UNIQUE INDEX job_response_unique ON research_jobs(json_extract(data,'$.response_id')) WHERE json_extract(data,'$.deleted_at') IS NULL AND json_extract(data,'$.response_id') IS NOT NULL;
CREATE UNIQUE INDEX usage_month_unique ON usage(json_extract(data,'$.month'));
CREATE UNIQUE INDEX sync_collector_unique ON sync_status(json_extract(data,'$.collector_id'));
CREATE INDEX audit_target ON audit(json_extract(data,'$.table'),json_extract(data,'$.row_id'));
CREATE TRIGGER audit_immutable_update BEFORE UPDATE ON audit BEGIN SELECT RAISE(ABORT,'immutable history'); END;
CREATE TRIGGER audit_immutable_delete BEFORE DELETE ON audit BEGIN SELECT RAISE(ABORT,'immutable history'); END;
CREATE TRIGGER audit_corrections_immutable_update BEFORE UPDATE ON audit_corrections BEGIN SELECT RAISE(ABORT,'immutable history'); END;
CREATE TRIGGER audit_corrections_immutable_delete BEFORE DELETE ON audit_corrections BEGIN SELECT RAISE(ABORT,'immutable history'); END;
CREATE TRIGGER changes_immutable_update BEFORE UPDATE ON changes BEGIN SELECT RAISE(ABORT,'immutable history'); END;
CREATE TRIGGER changes_immutable_delete BEFORE DELETE ON changes BEGIN SELECT RAISE(ABORT,'immutable history'); END;
